#!/usr/bin/env python3
"""
Generate `codex/data/` and the card art under `codex/images/` from the
Codex Card Database's repository and the Screentop module.

    python3 scripts/import_codex_cards.py
    python3 scripts/import_codex_cards.py --offline ~/src/codex-cards-gatsby
    python3 scripts/import_codex_cards.py --no-images

The texts, the rulings and every card's numbers are the ten `raw_data`
files of rgdelato/codex-cards-gatsby (the source of codexcarddb.com) at
the commit pinned in `SOURCE_SHA`, so a re-import is the same import
until somebody moves the pin. `--offline <dir>` reads the same ten files
from a local checkout (the repository's root or its `raw_data/`).

It writes, whole and sorted by slug:

- `codex/data/cards.json` -- every record that is not a hero, with a
  `kind`: `card` (a starting card or a codex card), `token`, `building`
  or `worker`. Two records with one name (a token's two faces, each
  colour's copy of the worker card) collapse to the first.
- `codex/data/heroes.json` -- the twenty heroes, each with its three
  bands as `{min_level, atk, hp, text}`.
- `codex/data/rulings.json` -- Sirlin's rulings: the `General` group's
  keyword rulings, and every other group's by the card they name.

A card is keyed by its slug, the database's own (`toSlug` in its
`createCardJSONData.js`): lowercase, whitespace to underscores, every
other non-word character dropped -- `trojan_duck`, `regularsized_rhinoceros`.
The glyphs in the texts become tokens the way `codex/tokens.py` reads
them: ⤵ `{exhaust}`, ◎ `{target}`, ① ② ... `{gold:n}`, → `{arrow}`.
The `rules_text_1..3` lines become a list. Nothing else is reworded.

The art comes in the same run, unless `--no-images`:

- every card's and hero's picture, by its `sirlins_filename`, from the
  database's image host into `codex/images/cards/<slug>.jpg` (330 by
  450; tokens, workers and buildings have none there);
- from the Screentop module @GRAG/Codex, whose spec one GraphQL query
  returns with every sheet's URL, into `codex/images/board/`: each sheet
  in `BOARD_SHEETS` cut into the cells pinned for it. A sheet whose
  cells are not pinned yet is saved whole as `sheets/<name>.png` and
  reported, so pinning it is one look.

Everything it writes is regenerated by re-running it and never edited by
hand -- the rule `d12ball/data/` lives under (docs/design/codex.md, "The
cards are data").
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "codex" / "data"
CARD_IMAGE_DIR = PROJECT_ROOT / "codex" / "images" / "cards"
BOARD_IMAGE_DIR = PROJECT_ROOT / "codex" / "images" / "board"

#: rgdelato/codex-cards-gatsby's master on 2026-10-08 (its last commit
#: is of 2019-11-04). Move it to take a newer import.
SOURCE_SHA = "10f8952c2258e3ed16d6654d05043e7e55e574ec"
SOURCE_URL = (
    "https://raw.githubusercontent.com/rgdelato/codex-cards-gatsby/"
    f"{SOURCE_SHA}/raw_data/"
)
#: The database's picture of a card, by its `sirlins_filename`.
CARD_IMAGE_URL = "http://codexcards-assets.surge.sh/images/"
SCREENTOP_API = "https://api.screentop.gg/"
SCREENTOP_QUERY = (
    '{ user(name:"GRAG"){ game(name:"Codex"){ revision(name:"main"){ spec '
    "} } } }"
)

#: The non-hero files, in the order a duplicate name keeps its first.
CARD_FILES = (
    "neutral.json", "red.json", "green.json", "blue.json",
    "black.json", "white.json", "purple.json",
)
SOURCE_FILES = CARD_FILES + ("heroes.json", "maps.json", "rulings.json")

HEADER_NOTE = (
    "Regenerated whole by scripts/import_codex_cards.py from the source "
    "below; never edited by hand."
)

#: The Screentop sheets the board draws from, by the name the module's
#: spec gives each, and the cells cut out of it: `(columns, rows)` of the
#: sheet's grid, and `{output name: cell index}` read left to right, top
#: to bottom from 0. `None` for the cells is a sheet nobody has looked at
#: yet: it is saved whole under `sheets/` and reported, never guessed.
#: `"whole"` keeps the sheet as one picture.
BOARD_SHEETS: dict[str, tuple[tuple[int, int] | None, dict[str, int] | str | None]] = {
    "Playmat": (None, "whole"),
    # The Base, Tech I, II and III tiles, the four add-on cards, the five
    # patrol-slot icons and the twenty spec cards.
    "Mini Cards": ((10, 4), None),
    # The card, hero and token backs.
    "Card Backs": (None, None),
    # The Dancer, Angry Dancer and Mercenary faces.
    "Token and Map Cards": (None, None),
    "Damage": (None, None),
    "Levels": (None, None),
    "Time Runes": (None, None),
    "Chits": (None, None),
}

GLYPHS = {"⤵": "{exhaust}", "◎": "{target}", "→": "{arrow}"}
#: ⓪ and ① to ⑳.
CIRCLED_DIGITS = {"⓪": 0, **{chr(0x2460 + n - 1): n for n in range(1, 21)}}


def to_slug(name: str) -> str:
    """The database's slug: lowercase, whitespace to `_`, every other
    non-word character dropped."""
    return re.sub(r"\W", "", re.sub(r"\s", "_", name.lower()))


def tokenize(text: str) -> str:
    """The text with its glyphs turned into tokens and nothing else
    changed."""
    out = []
    for character in text:
        if character in GLYPHS:
            out.append(GLYPHS[character])
        elif character in CIRCLED_DIGITS:
            out.append(f"{{gold:{CIRCLED_DIGITS[character]}}}")
        else:
            out.append(character)
    return "".join(out)


def card_kind(record: dict) -> str:
    zone = record.get("starting_zone")
    if zone == "worker":
        return "worker"
    if zone == "trash":
        return "building" if "Building" in record.get("type", "") else "token"
    return "card"


def text_lines(record: dict, keys: tuple[str, ...]) -> list[str]:
    return [tokenize(record[key]) for key in keys if record.get(key)]


def import_card(record: dict) -> dict:
    card = {
        "slug": to_slug(record["name"]),
        "name": record["name"],
        "kind": card_kind(record),
        "type": record.get("type"),
        "subtype": record.get("subtype"),
        "color": record.get("color"),
        "spec": record.get("spec"),
        "starting_zone": record.get("starting_zone"),
        "cost": record.get("cost"),
        "tech_level": record.get("tech_level"),
        "atk": record.get("ATK"),
        "hp": record.get("HP"),
        "target_icon": bool(record.get("target_icon", False)),
        "text": text_lines(record, ("rules_text_1", "rules_text_2", "rules_text_3")),
        "flavor_text": tokenize(record["flavor_text"]) if record.get("flavor_text") else None,
        "sirlins_filename": picture_name(record),
    }
    return card


def picture_name(record: dict) -> str | None:
    """The image host's file name -- with the database's own fix for
    "Research & Development", whose `&` the host dropped."""
    name = record.get("sirlins_filename")
    return name.replace("&", "") if name else None


def import_hero(record: dict) -> dict:
    bands = []
    for band, min_level, prefix in (
        (1, 1, "base_text"),
        (2, record["mid_level"], "mid_text"),
        (3, record["max_level"], "max_text"),
    ):
        bands.append({
            "min_level": min_level,
            "atk": record[f"ATK_{band}"],
            "hp": record[f"HP_{band}"],
            "text": text_lines(record, (f"{prefix}_1", f"{prefix}_2")),
        })
    return {
        "slug": to_slug(record["name"]),
        "name": record["name"],
        "color": record.get("color"),
        "spec": record.get("spec"),
        "subtype": record.get("subtype"),
        "cost": record["cost"],
        "max_level": record["max_level"],
        "bands": bands,
        "sirlins_filename": picture_name(record),
    }


def import_rulings(groups: dict) -> dict:
    """
    The `General` group by keyword, every other group by the card each
    ruling names. A row naming two records ("Dancer / Angry Dancer")
    rules on each. A row with no ruling (the source carries an ability's
    text alone on some) gives its ability text and nothing else.
    """
    def collect(rows: list[dict], split: bool) -> list[dict]:
        entries: dict[str, dict] = {}
        for row in rows:
            names = [n.strip() for n in row["card"].split(" / ")] if split else [row["card"]]
            for name in names:
                entry = entries.setdefault(to_slug(name), {
                    "slug": to_slug(name),
                    "name": name,
                    "ability_text": None,
                    "rulings": [],
                })
                if row.get("abilityText") and not entry["ability_text"]:
                    entry["ability_text"] = tokenize(row["abilityText"])
                if row.get("ruling"):
                    entry["rulings"].append({
                        "author": row.get("author"),
                        "date": (row.get("date") or "")[:10] or None,
                        "text": tokenize(row["ruling"]),
                    })
        return sorted(entries.values(), key=lambda entry: entry["slug"])

    cards: list[dict] = []
    for group, rows in groups.items():
        if group == "General":
            continue
        for entry in collect(rows, split=True):
            entry["group"] = group
            cards.append(entry)
    merged: dict[str, dict] = {}
    for entry in cards:
        if entry["slug"] in merged:
            merged[entry["slug"]]["rulings"].extend(entry["rulings"])
        else:
            merged[entry["slug"]] = entry
    return {
        "general": collect(groups["General"], split=False),
        "cards": sorted(merged.values(), key=lambda entry: entry["slug"]),
    }


def build(sources: dict[str, object], source_label: str) -> dict[str, dict]:
    cards: dict[str, dict] = {}
    for name in CARD_FILES:
        for record in sources[name]:
            card = import_card(record)
            cards.setdefault(card["slug"], card)
    heroes = {hero["slug"]: hero for hero in map(import_hero, sources["heroes.json"])}
    clash = set(cards) & set(heroes)
    if clash:
        raise SystemExit(f"a hero and a card share a slug: {sorted(clash)}")
    header = {"note": HEADER_NOTE, "source": source_label}
    return {
        "cards.json": {**header, "cards": [cards[slug] for slug in sorted(cards)]},
        "heroes.json": {**header, "heroes": [heroes[slug] for slug in sorted(heroes)]},
        "rulings.json": {**header, **import_rulings(sources["rulings.json"])},
    }


def fetch(url: str, data: bytes | None = None, headers: dict | None = None) -> bytes:
    request = urllib.request.Request(url, data=data, headers={
        "User-Agent": "fool-bot codex import", **(headers or {}),
    })
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def read_sources(offline: Path | None) -> tuple[dict[str, object], str]:
    if offline is None:
        return (
            {name: json.loads(fetch(SOURCE_URL + name)) for name in SOURCE_FILES},
            SOURCE_URL,
        )
    folder = offline / "raw_data" if (offline / "raw_data").is_dir() else offline
    return (
        {name: json.loads((folder / name).read_text(encoding="utf-8")) for name in SOURCE_FILES},
        SOURCE_URL,
    )


def write_data(files: dict[str, dict]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for name, payload in files.items():
        (DATA_DIR / name).write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"wrote {DATA_DIR / name}")


def import_card_art(files: dict[str, dict]) -> list[str]:
    """Every card's and hero's picture; the slugs that failed."""
    CARD_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    failed = []
    records = files["cards.json"]["cards"] + files["heroes.json"]["heroes"]
    for record in records:
        if not record.get("sirlins_filename"):
            continue
        try:
            picture = fetch(CARD_IMAGE_URL + record["sirlins_filename"])
        except OSError as error:
            failed.append(f"{record['slug']} ({error})")
            continue
        (CARD_IMAGE_DIR / f"{record['slug']}.jpg").write_bytes(picture)
    return failed


def screentop_sheets() -> dict[str, str]:
    """Every asset of the module's spec, by name, as its URL."""
    body = json.dumps({"query": SCREENTOP_QUERY}).encode()
    answer = json.loads(fetch(SCREENTOP_API, body, {"Content-Type": "application/json"}))
    spec = answer["data"]["user"]["game"]["revision"]["spec"]
    if isinstance(spec, str):
        spec = json.loads(spec)
    entries = spec["assets"]["entries"]
    if isinstance(entries, dict):
        entries = list(entries.values())
    return {entry["name"]: entry["url"] for entry in entries if entry.get("url")}


def import_board_art() -> list[str]:
    """The Screentop sheets' cells; what is left for somebody to pin."""
    from PIL import Image

    BOARD_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    urls = screentop_sheets()
    unpinned = []
    for sheet, (grid, cells) in BOARD_SHEETS.items():
        if sheet not in urls:
            unpinned.append(f"{sheet}: not in the module's spec ({sorted(urls)})")
            continue
        image = Image.open(io.BytesIO(fetch(urls[sheet]))).convert("RGBA")
        stem = to_slug(sheet)
        if cells == "whole":
            image.save(BOARD_IMAGE_DIR / f"{stem}.png")
            continue
        if grid is None or cells is None:
            (BOARD_IMAGE_DIR / "sheets").mkdir(exist_ok=True)
            image.save(BOARD_IMAGE_DIR / "sheets" / f"{stem}.png")
            unpinned.append(f"{sheet}: saved whole at {image.size}; pin its grid and cells")
            continue
        columns, rows = grid
        width, height = image.width // columns, image.height // rows
        for name, index in cells.items():
            column, row = index % columns, index // columns
            cell = image.crop((column * width, row * height, (column + 1) * width, (row + 1) * height))
            cell.save(BOARD_IMAGE_DIR / f"{name}.png")
    return unpinned


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[1].strip())
    parser.add_argument("--offline", type=Path, help="a local checkout of codex-cards-gatsby")
    parser.add_argument("--no-images", action="store_true", help="the data alone")
    options = parser.parse_args()

    sources, label = read_sources(options.offline)
    files = build(sources, label)
    write_data(files)
    if options.no_images:
        return 0
    failed = import_card_art(files)
    for line in failed:
        print(f"card art not fetched: {line}", file=sys.stderr)
    unpinned = import_board_art()
    for line in unpinned:
        print(f"board art: {line}", file=sys.stderr)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
